### ISSUE TITLE
Error markWatched

### ISSUE THREAD

**Issue by sergiookey** [seanwlk/tvtimewrapper#1]
Congratulation for your great work. I use your library for extract information of TV Time.

markWatched not work. Can you see it?

Thank your very much.

**Comment by seanwlk** [comment]
Hi i ran some test and indeed the watch status is not being set even though the reply from server is correct. I will dig into it. The same happens with all the other methods that aren't just straight up GET requests.

EDIT
I reverse engineered the Android app and handled to get access to the native APIs. I will update the library accordingly and add plenty of other methods.

**Comment by sergiookey** [comment]
Great. If you need help I can collaborate. If you provide me with the calls you get for reverse engineering, I can try to make them too.

Thank you very much and very good work.

**Comment by seanwlk** [comment]
> Great. If you need help I can collaborate. If you provide me with the calls you get for reverse engineering, I can try to make them too.
> 
> Thank you very much and very good work.

I already finished implementing the ones i recognized as useful for basic user. Library is ready im making a proper documentation for it.

**Comment by sergiookey** [comment]
Thank you very much. I am looking forward to using your library again.

**Comment by seanwlk** [comment]
Check it out 1537eb84580ad55eceb598a944598bd3570b55ee

Be careful i broke the whole API returns from before, these are native APIs now.

check docs here: https://seanwlk.github.io/tvtimewrapper/

**Comment by sergiookey** [comment]
Exception: Can not log-in. 

Library update from 0.0.2 to 0.0.3.

Thank you very much.

**Comment by seanwlk** [comment]
works on my end, tried with multiple accounts. If that exception is risen upon instance creation then the credentials must be actually wrong.
Refer to these lines: https://github.com/seanwlk/tvtimewrapper/blob/master/tvtimewrapper/__init__.py#L24-L27

**Comment by sergiookey** [comment]
Python 3.8.2 windows 10

Can you send username and password for private? Thank you

**Comment by seanwlk** [comment]
> Python 3.8.2 windows 10
> 
> Can you send username and password for private? Thank you

Environment doesn't matter in this case. I run it on windows Linux and on 3 different versions of python (3.6, 3.7 and 3.8.7) I'm not gonna share my credentials not even of test accounts. You can create one yourself with 10minutemail or with a gmail alias if you want to test.

I'm sure the login method is correct since it's literally the one used in the Android App

Is you account by any chance originally registered with twitter/Facebook and not a native TVtime account?

**Comment by sergiookey** [comment]
It already works for me. A new account was required. Great job. Thank you very much.

**Comment by seanwlk** [comment]
It's strange because I tested it with existing accounts and had no issues.
Glad it works anyway.
