### ISSUE TITLE
{'error': {'code': 500, 'message': None}}

### ISSUE THREAD

**Issue by vinedu18** [seanwlk/tvtimewrapper#3]
hello on use tvtime.show.myShows() i have this error mesage

**Comment by seanwlk** [comment]
Hi, sorry for the late reply, i checked that method and i believe it was deprecated by the developers in favor of the new backend they seem to be using for the movies part of the application. It doesnt seem to be using any API calls anymore but using builtin methods of the application.
At the moment the only thing that comes up in my mind is to get this data from the website. You could add this function to your code for instance:

```
from tvtimewrapper import TVTimeWrapper
import re
import html
import ast
import json

tvtime = TVTimeWrapper("seanwlk","XXXXXXXXXXXXXXXXXXXXXXXXX")

def myShows(uid):
  r = tvtime.session.get(f"https://www.tvtime.com/en/user/{uid}/profile").text
  compiledRE = re.compile('tvst.data = ({.*?});', re.DOTALL)
  d = compiledRE.search(r).group(1)
  d = ast.literal_eval(d.replace("'",'"').replace("shows :",'"shows":').replace("profile :",'"profile":'))
  shows = json.loads(html.unescape(d['shows']).replace("\\",""))
  return shows
  

print(myShows(tvtime.userId))
```

**Comment by sergiookey** [comment]
Thank you very much. Great work.
